name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install bats-core from source
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        ./install.sh /usr/local

    - name: Run BATS suite
      run: bats -r tests
