name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup BATS
      uses: mig4/setup-bats@v1.0.1
      with:
        bats-version: 1.1.0

    - name: Run BATS suite
      run: bats -r tests
